# Form implementation generated from reading ui file '.\pdf_maker.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(512, 470)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.folder_line = QtWidgets.QLineEdit(self.centralwidget)
        self.folder_line.setObjectName("folder_line")
        self.horizontalLayout.addWidget(self.folder_line)
        self.select_folderBn = QtWidgets.QPushButton(self.centralwidget)
        self.select_folderBn.setMinimumSize(QtCore.QSize(80, 0))
        self.select_folderBn.setObjectName("select_folderBn")
        self.horizontalLayout.addWidget(self.select_folderBn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.folder_files = QtWidgets.QListView(self.centralwidget)
        self.folder_files.setObjectName("folder_files")
        self.verticalLayout_2.addWidget(self.folder_files)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pdf_file_line = QtWidgets.QLineEdit(self.centralwidget)
        self.pdf_file_line.setObjectName("pdf_file_line")
        self.horizontalLayout_2.addWidget(self.pdf_file_line)
        self.select_pdfBn = QtWidgets.QPushButton(self.centralwidget)
        self.select_pdfBn.setMinimumSize(QtCore.QSize(80, 0))
        self.select_pdfBn.setObjectName("select_pdfBn")
        self.horizontalLayout_2.addWidget(self.select_pdfBn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.save_attachmentsBn = QtWidgets.QPushButton(self.centralwidget)
        self.save_attachmentsBn.setMinimumSize(QtCore.QSize(80, 0))
        self.save_attachmentsBn.setObjectName("save_attachmentsBn")
        self.horizontalLayout_3.addWidget(self.save_attachmentsBn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 512, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PDF Maker"))
        self.select_folderBn.setText(_translate("MainWindow", "Select Folder"))
        self.checkBox.setText(_translate("MainWindow", "Select All"))
        self.select_pdfBn.setText(_translate("MainWindow", "Select PDF"))
        self.save_attachmentsBn.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
